"use client";

import { Activity, BarChart3, RadioTower } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const profile = [0, -1.8, -3.4, -5.1, -7.1, -8.43, -6.4, -4.1, -2.2].map((displacement_cm, distance_index) => ({ distance_index, displacement_cm }));
const forecast = [{ day: "T0", observed: -8.43, forecast: -8.43 }, { day: "+1", observed: null, forecast: -8.72 }, { day: "+2", observed: null, forecast: -9.08 }, { day: "+3", observed: null, forecast: -9.46 }, { day: "+4", observed: null, forecast: -9.91 }, { day: "+5", observed: null, forecast: -10.35 }, { day: "+6", observed: null, forecast: -10.82 }, { day: "+7", observed: null, forecast: -11.28 }];
const spectrum = [{ hz: 0, vehicle: .08, fracture: .02 }, { hz: 10, vehicle: .8, fracture: .12 }, { hz: 20, vehicle: .3, fracture: .2 }, { hz: 30, vehicle: .12, fracture: .28 }, { hz: 40, vehicle: .08, fracture: .42 }, { hz: 50, vehicle: .08, fracture: .62 }, { hz: 60, vehicle: .08, fracture: .92 }, { hz: 70, vehicle: .06, fracture: .55 }];

export default function AnalyticsDeck({ mode = "overview" }: { mode?: "overview" | "prediction" }) {
  return <section className={`analytics-deck ${mode === "prediction" ? "analytics-deck-full" : ""}`}><div className="deck-title"><div className="panel-kicker"><BarChart3 size={15} /> {mode === "prediction" ? "AI PREDICTIVE ENGINE" : "ANALYTICS & PREDICTION DECK"}</div><span>AI COG / CM</span></div><div className="chart-block"><div className="chart-block-head"><span>DISPLACEMENT VS FACE ADVANCE</span><b>{mode === "prediction" ? "7-DAY DERIVED PROPAGATION" : "MACRO PROFILE"}</b></div><div className="recharts-wrap"><ResponsiveContainer width="100%" height={mode === "prediction" ? 230 : 150}><AreaChart data={(mode === "prediction" ? forecast : profile) as any}><defs><linearGradient id="cyanFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00e5ff" stopOpacity={.38} /><stop offset="100%" stopColor="#00e5ff" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#1e293b" strokeDasharray="3 3" /><XAxis dataKey={mode === "prediction" ? "day" : "distance_index"} stroke="#8493a1" fontSize={10} tickLine={false} /><YAxis stroke="#8493a1" fontSize={10} tickLine={false} unit=" cm" /><Tooltip contentStyle={{ background: "#0e1626", border: "1px solid #1e293b", fontFamily: "JetBrains Mono" }} /><Area type="monotone" dataKey={mode === "prediction" ? "forecast" : "displacement_cm"} stroke="#00e5ff" fill="url(#cyanFill)" strokeWidth={2} connectNulls /></AreaChart></ResponsiveContainer></div></div><div className="chart-block"><div className="chart-block-head"><span><RadioTower size={13} /> FREQUENCY SIGNATURE</span><b>10 Hz VEHICLE / 60 Hz ROCK FRACTURE</b></div><div className="recharts-wrap"><ResponsiveContainer width="100%" height={mode === "prediction" ? 210 : 145}><LineChart data={spectrum}><CartesianGrid stroke="#1e293b" strokeDasharray="3 3" /><XAxis dataKey="hz" stroke="#8493a1" fontSize={10} unit=" Hz" /><YAxis stroke="#8493a1" fontSize={10} /><Tooltip contentStyle={{ background: "#0e1626", border: "1px solid #1e293b", fontFamily: "JetBrains Mono" }} /><Line type="monotone" dataKey="vehicle" stroke="#ffb300" dot={false} strokeWidth={2} /><Line type="monotone" dataKey="fracture" stroke="#ff3d71" dot={false} strokeWidth={2} /></LineChart></ResponsiveContainer></div></div><div className="analytics-legend"><span><i className="legend-cyan" /> AI displacement surface</span><span><i className="legend-amber" /> Vehicle rumble</span><span><i className="legend-red" /> Fracture signature</span></div><div className="analytics-disclaimer"><Activity size={14} /> The 7-day curve is a derived risk projection from the supplied single-date AI displacement surface; it is not an observed temporal series.</div></section>;
}
